version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 192.168.123.123:80 --settings=music_player.settings.prod"
    volumes:
      - .:/website
      - ~/docker/music:/music
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db